// Banco: Ciências — Astronomia e a Terra (40 pares de cartas iguais: desenho + nome).
// Os desenhos estão em desenhos/astronomia.js. Fases da Lua como se vê do Brasil (hemisfério sul).
// Para editar: mude o texto entre aspas. Mantenha as chaves, as aspas e a vírgula no fim da linha.
registrarBancoMemoria({
  titulo: "Ciências — Astronomia e a Terra",
  pares: [
    { igual: { imagem: "sol", texto: "Sol" } },
    { igual: { imagem: "lua-cheia", texto: "Lua Cheia" } },
    { igual: { imagem: "lua-nova", texto: "Lua Nova" } },
    { igual: { imagem: "lua-crescente", texto: "Lua Crescente" } },
    { igual: { imagem: "lua-minguante", texto: "Lua Minguante" } },
    { igual: { imagem: "quarto-crescente", texto: "Quarto Crescente" } },
    { igual: { imagem: "quarto-minguante", texto: "Quarto Minguante" } },
    { igual: { imagem: "gibosa-crescente", texto: "Gibosa Crescente" } },
    { igual: { imagem: "gibosa-minguante", texto: "Gibosa Minguante" } },
    { igual: { imagem: "eclipse-solar", texto: "Eclipse Solar" } },
    { igual: { imagem: "eclipse-lunar", texto: "Eclipse Lunar" } },
    { igual: { imagem: "terra", texto: "Terra" } },
    { igual: { imagem: "terra-inclinada", texto: "Terra Inclinada (eixo)" } },
    { igual: { imagem: "orbita-terra-sol", texto: "Órbita Terra-Sol" } },
    { igual: { imagem: "sol-terra-lua", texto: "Sol, Terra e Lua" } },
    { igual: { imagem: "estrela", texto: "Estrela" } },
    { igual: { imagem: "cruzeiro-do-sul", texto: "Cruzeiro do Sul" } },
    { igual: { imagem: "via-lactea", texto: "Via Láctea" } },
    { igual: { imagem: "telescopio", texto: "Telescópio" } },
    { igual: { imagem: "satelite", texto: "Satélite" } },
    { igual: { imagem: "foguete", texto: "Foguete" } },
    { igual: { imagem: "astronauta", texto: "Astronauta" } },
    { igual: { imagem: "saturno", texto: "Saturno" } },
    { igual: { imagem: "marte", texto: "Marte" } },
    { igual: { imagem: "venus", texto: "Vênus" } },
    { igual: { imagem: "cometa", texto: "Cometa" } },
    { igual: { imagem: "estrela-cadente", texto: "Estrela Cadente" } },
    { igual: { imagem: "relogio", texto: "Relógio (fuso horário)" } },
    { igual: { imagem: "bussola", texto: "Bússola" } },
    { igual: { imagem: "globo-meridianos", texto: "Globo com Meridianos" } },
    { igual: { imagem: "hemisferios", texto: "Hemisférios Norte e Sul" } },
    { igual: { imagem: "navio-horizonte", texto: "Navio no Horizonte" } },
    { igual: { imagem: "vareta-sombra", texto: "Vareta com Sombra" } },
    { igual: { imagem: "mapa-mundi", texto: "Mapa-múndi" } },
    { igual: { imagem: "nuvem", texto: "Nuvem" } },
    { igual: { imagem: "raios-de-sol", texto: "Raios de Sol" } },
    { igual: { imagem: "dia-e-noite", texto: "Dia e Noite" } },
    { igual: { imagem: "calendario", texto: "Calendário (365 dias)" } },
    { igual: { imagem: "ampulheta", texto: "Ampulheta" } },
    { igual: { imagem: "constelacao", texto: "Constelação" } },
  ]
});
